1 = "Card(001, Sword)"
2 = "Card(002, Bow)"
3 = "Card(003, Shield)"
4 = "Card(004, Sword and shield)"
5 = "Card(005, Great sword)"
6 = "Card(006, Push-up)"
7 = "Card(007, Fireball)"
8 = "Card(008, Venom)"
9 = "Card(009, Perfusion)"
10 = "Card(010, Bandage)"
11 = "Card(011, Recharge)"
12 = "Card(012, Harden)"
13 = "Card(013, Spike)"
14 = "Card(014, Sleeping dart)"
15 = "Card(015, Bash)"
16 = "Card(016, Vampirism)"
17 = "Card(017, Toxic cloud)"
18 = "Card(018, Ashes)"
19 = "Card(019, Mud trap)"
20 = "Card(020, Elemental storm)"
21 = "Card(021, Fire wall)"
22 = "Card(022, Turtle stand)"
23 = "Card(023, Empty card)"
24 = "Card(024, Cheat card)"
25 = "Card(025, Growl)"
26 = "Card(026, Bite)"
27 = "Card(027, Baseball bat)"
28 = "Card(028, Intimidation)"
29 = "Card(029, Bag shot)"
30 = "Card(030, Denture bite)"
31 = "Card(031, High blood pressure pill)"
32 = "Card(032, )"
