[0]
name = "Scroll of strenght"
trigger = "start of combat"
strenght = 1
description = "Start the combat with {augment.strenght} more strenght."

[1]
name = "Scroll of resistance"
trigger = "start of combat"
resistance = 1
description = "Start the combat with {augment.resistance} more resistance."

[2]
name = "Scroll of health"
trigger = "get"
max_hp = 10
description = "Get {augment.max_hp} maximum health."
