[0]
name = "Scroll of strenght"
trigger = "start of combat"
strenght = 1

[1]
name = "Scroll of resistance"
trigger = "start of combat"
resistance = 1

[2]
name = "Scroll of health"
trigger = "get"
max_hp = 10
