[0]
name = "Dumbo"
hp = 500
energy = 1
hand_size = 1
deck = [23]

[1]
name = "First One"
hp = 20
energy = 2
hand_size = 2
deck = [2, 2, 3, 4]

[2]
name = "First Two"
hp = 20
energy = 2
hand_size = 2
deck = [1, 1, 1, 1]

[3]
name  = "The Third"
hp = 30
energy = 2
hand_size = 2
deck = [1, 1, 2, 2]

[4]
name = "No Pain No Gain"
hp = 70
energy = 4
hand_size = 4
deck = [6, 6, 6, 6, 6, 6, 2, 2]
