[0]
name = "Dumbo"
hp = 500
energy = 1
hand_size = 1
deck = [23]

[1]
name = "Stray dog"
hp = 20
energy = 2
hand_size = 1
deck = [25, 25, 26, 26, 26]

[2]
name = "Bully"
hp = 20
energy = 2
hand_size = 3
deck = [27, 27, 28, 28]

[3]
name  = "Angry Grandma"
hp = 20
energy = 2
hand_size = 4
deck = [29, 29, 29, 29, 30]

[4]
name = "No Pain No Gain"
hp = 70
energy = 4
hand_size = 4
deck = [6, 6, 6, 6, 6, 6, 2, 2]
