[Lisa]
hp = 80
energy = 2
hand_size = 4
deck = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[number_one]
hp = 20
energy = 2
hand_size = 2
deck = [2, 2, 3, 4]

[number_two]
hp = 20
energy = 2
hand_size = 2
deck = [1, 1, 1, 1]

[number_three]
hp = 30
energy = 2
hand_size = 2
deck = [1, 1, 2, 2]
