[Lisa]
hp = 80
energy = 2
hand_size = 2
deck = [1, 1, 1, 1, 3, 3, 4, 4, 5, 5]

[number_one]
hp = 10
energy = 2
hand_size = 1
deck = [2, 2, 3, 4]

[number_two]
hp = 10
energy = 3
hand_size = 2
deck = [1, 1, 1, 1]
