[0]
name = "Tester"
hp = 500
energy = 5
hand_size = 8
deck = []
playable = true

[1]
name = "Lisa"
hp = 80
energy = 2
hand_size = 4
deck = [24, 24, 24, 24, 24, 24]

[2]
name = "Warrior"
hp = 60
energy = 2
hand_size = 5
deck = [3, 3, 1, 1, 1, 1, 1, 6, 16]

[3]
name = "Staller"
hp = 60
energy = 2
hand_size = 5
deck = [3, 3, 4, 4, 4, 4, 4, 12, 15]
